### ISSUE TITLE
OCI prereqs link in the readme is broken

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle/oci-sap-dev#1]
The link https://github.com/cloud-partners/oci-prerequisites returns a 404 error.

**Comment by gilsonmelo** [comment]
that's happening because the link is redirecting to oci-quickstart (https://github.com/oci-quickstart/oci-prerequisites) which is private now. OCI PM team is working on it to make that repo public again.

**Comment by gilsonmelo** [comment]
Closing this issue
